# Generated by Django 5.1.3 on 2024-11-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
